# SPDX-FileCopyrightText: Copyright (C) Arduino s.r.l. and/or its affiliated companies
#
# SPDX-License-Identifier: MPL-2.0

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "arduino-app-bridge"
version = "0.1.0"
authors = [
  { name="Marco Colombo", email="m.colombo@arduino.cc" },
  { name="Roberto Gazia", email="r.gazia@arduino.cc" },
]
description = "MessagePack-RPC bridge between Python apps and Arduino microcontrollers"
readme = "README.md"
requires-python = ">=3.10"
license = "MPL-2.0"
license-files = ["LICENSE.txt"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
dependencies = [
    "msgpack>=1.0.0",
]

[dependency-groups]
dev = [
    "build",
    "pytest",
    "reuse[charset-normalizer]",
    "ruff",
]

[project.urls]
"Homepage" = "https://github.com/arduino/arduino-app-bridge"

[tool.ruff]
line-length = 120

[tool.setuptools.packages.find]
where = ["src"]
include = ["arduino.app_bridge*"]

[tool.setuptools.package-data]
"arduino.app_bridge" = ["py.typed"]
